import Head from "next/head";
import { Geist, Geist_Mono } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function Home() {
  // console.log(styles);
  return (
    <>
      <Head>
        <title>The blog Hunting coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta
          name="keywords"
          content="nextjs, huntingcoder blog, hunting coder"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* <Script src="/src.js" strategy="lazyOnload"></Script> */}

      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <main className={styles.main}>
          <h1 className={styles.title}>Welcome to the blog of Hunting coder</h1>
          <div className={styles.huntcoder}>
            <h4>A blog for hunting coder by a coder</h4>
          </div>

          <div className={styles.blogs}>
            <div className={styles.popblogs}>
              <h2>Popular Blogs</h2>
            </div>
            <div className={styles.blogitem}>
              <h2>How to learn javascript in 2025 ?</h2>
              <p>Java script is used to build a logic for the web</p>
              <Link href="/blog" className={styles.btnhome}>
                Read More
              </Link>
            </div>
            <div className={styles.blogitem}>
              <h2>How to learn javascript in 2025 ?</h2>
              <p>Java script is used to build a logic for the web</p>
              <Link href="/blog" className={styles.btnhome}>
                Read More
              </Link>
            </div>
            <div className={styles.blogitem}>
              <h2>How to learn javascript in 2025 ?</h2>
              <p>Java script is used to build a logic for the web</p>
              <Link href="/blog" className={styles.btnhome}>
                Read More
              </Link>
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
